stages:
  - build
  - deploy

variables:
  HARBOR_REGISTRY: whiteregistry.cuyows.tcloud.ar
  HARBOR_PROJECT: whitecicd-pipeline
  DESTINATION_PROJECT: power-metrics
  HARBOR_USER: admin
  HARBOR_PASSWORD: TefAr123
  GIT_STRATEGY: none

build-ssh:
  stage: build
  variables:
    IMAGE_NAME: potencia-sfp-prometehus-dell-ssh
    APP_CONTEXT: app-ssh
  rules:
    - changes:
        - app-ssh/**/*
        - .gitlab-ci.yml
        - scripts/build.sh
      when: always
    - when: never
  image:
    name: $HARBOR_REGISTRY/$HARBOR_PROJECT/kaniko-git:debug
    entrypoint: [""]
  before_script:
    - git clone https://gitlab+deploy-token-3:${GIT_DEPLOY_TOKEN}@whitecicd-tt.cuyows.tcloud.ar/operaciones-red-cloud/potencia-sfp-prometheus.git .
  script:
    - sh scripts/build.sh

build-api:
  stage: build
  variables:
    IMAGE_NAME: potencia-sfp-prometheus-dell-api
    APP_CONTEXT: app-api
  rules:
    - changes:
        - app-api/**/*
        - .gitlab-ci.yml
        - scripts/build.sh
      when: always
    - when: never
  image:
    name: $HARBOR_REGISTRY/$HARBOR_PROJECT/kaniko-git:debug
    entrypoint: [""]
  before_script:
    - git clone https://gitlab+deploy-token-3:${GIT_DEPLOY_TOKEN}@whitecicd-tt.cuyows.tcloud.ar/operaciones-red-cloud/potencia-sfp-prometheus.git .
  script:
    - sh scripts/build.sh

update-tag:
  stage: deploy
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|cicd-fix)$/
      when: always
    - when: never
  before_script:
    - apk add --no-cache curl git
  script:
    - git clone https://gitlab+deploy-token-3:${GIT_DEPLOY_TOKEN}@whitecicd-tt.cuyows.tcloud.ar/operaciones-red-cloud/potencia-sfp-prometheus.git .
    - sed -i "s|^  tag: .*|  tag: ${CI_COMMIT_SHORT_SHA}|" deploy/values.yaml
    - git config user.name "GitLab CI"
    - git config user.email "ci@whitecicd"
    - git add deploy/values.yaml
    - git diff --cached --quiet || git commit -m "chore: update image tag to ${CI_COMMIT_SHORT_SHA} [skip ci]"
    - git push origin HEAD:"${CI_COMMIT_BRANCH}"
