stages:
  - build

variables:
  HARBOR_REGISTRY: whiteregistry.cuyows.tcloud.ar
  HARBOR_PROJECT: whitecicd-pipeline
  IMAGE_NAME: potencia-sfp-prometehus-cm
  GIT_STRATEGY: none

build:
  stage: build
  image:
    name: $HARBOR_REGISTRY/$HARBOR_PROJECT/kaniko-git:debug
    entrypoint: [""]
  variables:
    DOCKER_CONFIG: /kaniko/.docker
  before_script:
    - mkdir -p $DOCKER_CONFIG
    - echo "{\"auths\":{\"$HARBOR_REGISTRY\":{\"auth\":\"$(echo -n ${HARBOR_USER}:${HARBOR_PASSWORD} | base64)\"}}}" > $DOCKER_CONFIG/config.json
    - git clone https://gitlab+deploy-token-1:${GIT_DEPLOY_TOKEN}@whitecicd-tt.cuyows.tcloud.ar/operaciones-red-cloud/potencia-sfp-prometheus.git .
  script:
    - /kaniko/executor
      --context ${CI_PROJECT_DIR}/app
      --dockerfile ${CI_PROJECT_DIR}/app/Dockerfile
      --destination $HARBOR_REGISTRY/$HARBOR_PROJECT/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
      --destination $HARBOR_REGISTRY/$HARBOR_PROJECT/$IMAGE_NAME:latest
