stages:
  - build

variables:
  HARBOR_REGISTRY: whiteregistry.cuyows.tcloud.ar
  HARBOR_PROJECT: whitecicd-pipeline
  DESTINATION_PROJECT: power-metrics
  HARBOR_USER: admin
  HARBOR_PASSWORD: TefAr123
  GIT_STRATEGY: none

build-ssh:
  stage: build
  variables:
    IMAGE_NAME: potencia-sfp-prometehus-dell-ssh
    APP_CONTEXT: app-ssh
  rules:
    - changes:
        - app-ssh/**/*
        - .gitlab-ci.yml
        - scripts/build.sh
        - scripts/update-manifest.sh
      when: always
    - when: never
  image:
    name: $HARBOR_REGISTRY/$HARBOR_PROJECT/kaniko-git:debug
    entrypoint: [""]
  before_script:
    - git clone https://gitlab+deploy-token-3:${GIT_DEPLOY_TOKEN}@whitecicd-tt.cuyows.tcloud.ar/operaciones-red-cloud/potencia-sfp-prometheus.git .
  script:
    - sh scripts/build.sh
    - sh scripts/update-manifest.sh

build-api:
  stage: build
  variables:
    IMAGE_NAME: potencia-sfp-prometheus-dell-api
    APP_CONTEXT: app-api
  rules:
    - changes:
        - app-api/**/*
        - .gitlab-ci.yml
        - scripts/build.sh
        - scripts/update-manifest.sh
      when: always
    - when: never
  image:
    name: $HARBOR_REGISTRY/$HARBOR_PROJECT/kaniko-git:debug
    entrypoint: [""]
  before_script:
    - git clone https://gitlab+deploy-token-3:${GIT_DEPLOY_TOKEN}@whitecicd-tt.cuyows.tcloud.ar/operaciones-red-cloud/potencia-sfp-prometheus.git .
  script:
    - sh scripts/build.sh
    - sh scripts/update-manifest.sh
