{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "potencia-site.serviceAccountName" . }}
  labels:
{{ include "potencia-site.labels" . | nindent 4 }}
{{- end -}}
