replicaCount: 1

image:
  repository: whiteregistry.cuyows.tcloud.ar/power-metrics/potencia-sfp-prometehus-cm
  tag: latest
  pullPolicy: IfNotPresent

site:
  name: ""
  environment: production

service:
  type: ClusterIP
  port: 5000
  targetPort: http

serviceAccount:
  create: true
  name: ""

fullnameOverride: ""
nameOverride: ""

existingSecret: ""

config:
  elementSsh: ""

resources: {}

probes:
  enabled: true
