apiVersion: v1
kind: Secret
metadata:
  name: repo-potencia-sfp
  namespace: whitecicd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  name: potencia-sfp
  url: https://whitecicd-tt.cuyows.tcloud.ar/operaciones-red-cloud/potencia-sfp-prometheus.git
  username: argocd-whitecicd-cuyo
  password: Mistica00..
  insecure: "true"
  project: operaciones-red-cloud
